before:
  hooks:
    - go mod download
builds:
  - skip: true
archives:
  - format_overrides:
      - goos: windows
        format: zip
release:
  github: {}
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append
changelog:
  skip: true
