before:
  hooks:
    - go mod download
builds:
  - skip: true
archives:
  - format_overrides:
      - goos: windows
        format: zip
release:
  github: {}
  prerelease: auto
  mode: append
changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - typo
      - chore
      - test
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
